server:
  port: 0
spring:
  cloud:
    stream:
      bindings:
        send:
          destination: song
          group: song-group
          durableSubscription: true
  rabbitmq:
    username: guest
    password: guest