server:
  port: 0
spring:
  cloud:
    stream:
      bindings:
        send:
          destination: notification
          group: notification-group
          durableSubscription: true
  rabbitmq:
    username: guest
    password: guest