server:
  port: 0
spring:
  cloud:
    stream:
      bindings:
        send:
          destination: songalbum
          group: songalbum-group
          durableSubscription: true
  rabbitmq:
    username: guest
    password: guest