hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000
spring:
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@userKeyResolver}"
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 5
      routes:
        - id: auth-server
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: songalbum
          uri: lb://songalbum-service
          predicates:
            - Path=/songalbum/**
          filters:
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback/static-message
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
