spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: song-album

  cloud:
    stream:
      bindings:
        send:
          destination: check-song
          group: song-service

  rabbitmq:
    username: guest
    password: guest
    port: 5672

server:
  servlet:
    context-path: /song-album


logging:
  level:
    web:
      org.springframework.web: DEBUG
