spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: song-album
server:
  servlet:
    context-path: /song-album

logging:
  level:
    web:
      org.springframework.web: DEBUG