
@startuml
    title : Create Song Album By Given User ID
    actor "User" as user
    participant "API Gateway" as api_gw
    participant "Auth-Service" as auth
    participant "Song-Album" as song_album

    
    user -> api_gw:  POST /api/song-album/albums
    api_gw -> auth: /authentication/oauth/check_token
    auth -> auth: authorize
    api_gw <- auth: http_status: 200
    api_gw -> song_album: POST /api/song-album/albums
    song_service -> song_album: perform create album logic
    api_gw <- song_album: http_status: 200
    user <- api_gw: http_status: 200
    
@enduml