@startuml
    title : Get Song Info By Given Song ID
    actor "User" as user
    participant "API Gateway" as api_gw
    participant "Auth-Service" as auth
    participant "Song-Alabum" as song_alabum

    user -> api_gw: GET /api/song-alabum/alabums/{id}
    api_gw -> auth: GET /authentication/oauth/check_token
    api_gw <- auth: http_status: 200
    api_gw -> song_alabum: GET /api/song-alabum/alabums/{id}
    api_gw <- song_alabum: http_status: 200
    user <- api_gw: http_status: 200
    
@enduml