@startuml
    title : Retreive All Available Songs By Given Album ID
    actor "User" as user
    participant "API Gateway" as api_gw
    participant "Auth-Service" as auth
    participant "Song-Alabum" as song_album

    user -> api_gw: GET /api/song-album/albums/{id}/songs
    api_gw -> auth: GET /authentication/oauth/check_token
    api_gw <- auth: http_status: 200
    api_gw -> song_album: GET /api/song-albums/albums/{id}/songs
    api_gw <- song_album: http_status: 200
    user <- api_gw: http_status: 200
    
@enduml